[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "{{ package_name }}"
version = "0.0.1"
description = "A Python package for {{ package_name }}"
authors = ["{{ author_name }} {author_email}"]
dependencies = []
